name: Build MCLauncher
on:
  #schedule:
  #  - cron: "30 2 1 * *"
  push:
    branches: [buildtest]
  workflow_dispatch:
  repository_dispatch:
    types: [build]

concurrency: 
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build MCLauncher
    runs-on: windows-2019
    strategy:
      matrix:
        compress-format: [7z]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1  
        
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
     
      - name: Restore NuGet Packages
        run: nuget restore MCLauncher.sln        

      - name: Build MCLauncher proj
        id: MCLauncher
        run: msbuild MCLauncher.sln /p:Configuration=Release /p:Platform=x64


      - name: Prepare release tag
        id: date
        run: echo "date=$(date +'v%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: add timestamp
        id: date2
        run: echo "date2=$(date +'v%Y_%m_%d')" >> $GITHUB_OUTPUT
      
  #    - name: rename files
  #     shell: bash
  #      id: rename
  #      run: cp "./output/${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}"  "./output/${{ steps.date2.outputs.date2 }}.${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}"

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/${{ steps.date2.outputs.date2 }}.${{ steps.MCLauncher.outputs.artifact }}.${{ matrix.compress-format }}
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true
